environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip
  - pip.exe install numpy
  - pip.exe install pyproj==1.9.6
  - pip.exe install --no-deps -r requirements.txt
  - pip.exe install -r requirements-dev.txt
  - python setup.py install

build: off

test_script:
  - python setup.py test

on_success:
  - coverage.exe run --source woudc_formats setup.py test
  - coverage.exe report -m
